---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  
  - name: Install the Epel repo
    dnf:
      name:
        - epel-release
      state: present
      update_cache: yes
      
  - name: Install postgresql reposity for Centos 8.x
    dnf:
      name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
      disable_gpg_check: yes
      state: present
    

  - name: Disable the built-in PostgreSQL module
    command: dnf -qy module disable postgresql
    args: 
      warn: no
    
  - name: Install Postgresql 14
    yum:
      name:
        - postgresql14-server
        - postgresql14-contrib
        - postgresql14-devel
      state: latest
      update_cache: yes

  - name: check pg_config current alternatives
    shell: alternatives --display pgsql-pg_config | grep Current | cat
    register: pg_config
    changed_when: false
    ignore_errors: true

  - name: ensure pg_config is set
    command: /usr/sbin/update-alternatives --install /usr/bin/pg_config pgsql-pg_config /usr/pgsql-14/bin/pg_config 1400
    when: not (pg_config.stdout is search('pgsql-14'))
      
#  - name: Install psycopg2
#    pip:
#      name: psycopg2-binary
#      state: present
  
  - name: Ensure PostgreSQL data directory exists
    file:
      path: "/var/lib/pgsql/14/data"
      owner: "postgres"
      group: "postgres"
      state: directory
      mode: 0700
      
  - name: Check if PostgreSQL database is initialized
    stat:
      path: "/var/lib/pgsql/14/data/PG_VERSION"
    register: pgdata_dir_version
    
  - name: Ensure PostgreSQL database is initialized
    command: "/usr/pgsql-14/bin/initdb -D /var/lib/pgsql/14/data"
    when: not pgdata_dir_version.stat.exists
    become: true
    become_user: "postgres"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
    vars:
      ansible_ssh_pipelining: true
    notify:
      - postgresql status
      
  - name: Create database
    postgresql_db:
      name: test
      encoding: UTF-8
      template: template0
      state: present
      
  handlers:
  - name: postgresql status
    service:
      name: postgresql-14.service
      state: started
      enabled: yes
